algoritmo "Quadrado perfeito aproximado"
var
// Variavel do Primeiro Programa
numero , raiz1: inteiro

//Variavel do Segundo Programa //


inicio
      escreva ("Informe um número para ser calculado: ")

      leia(numero)
      raiz1 <- 0

      repita
      raiz1 <- raiz1 + 1
      ate (raiz1 * raiz1) > numero


      raiz1 <- raiz1 - 1




      Escreval ("O Quadrado Perfeito mais Proximo é: ", raiz1)

      

fimalgoritmo